<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_first_name</name>
   <tag></tag>
   <elementGuidId>97e5bca3-ae97-4dcc-9781-b77dd7d7872f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_first_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_first_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First Name *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8091b28-cb7c-4276-aa86-23bd55a25d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b5646a9-d5da-4dc9-8dba-26978ad2a603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>537f8efd-ac09-4ff8-a611-ae1ed1815c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_first_name</value>
      <webElementGuid>c7b5815f-6c0d-480f-886f-f527c1bf5f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_first_name</value>
      <webElementGuid>d7e1d07b-5a82-4ae3-916f-88db82149ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>b2d85a4b-ef9a-455f-900f-9e1af9ffe8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_first_name&quot;)</value>
      <webElementGuid>398e6b04-0787-42e1-a5fb-f7e8ff848573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_first_name']</value>
      <webElementGuid>e5fa3d2d-5d81-4c51-a69d-8877701d5fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_first_name_field']/input</value>
      <webElementGuid>a218423c-a05e-461e-841d-7fc1d977e2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/input</value>
      <webElementGuid>0596a409-6007-4d17-90ab-f0d745e08aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_first_name' and @id = 'billing_first_name']</value>
      <webElementGuid>f073260b-5310-4b1e-b9b4-ba75fa7317a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
