<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_View Basket Android Quick Start Guide</name>
   <tag></tag>
   <elementGuidId>0abbd7c0-cf73-444b-971f-7cee04764ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;View Basket “Android Quick Start Guide” has been added to your basket.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d658e72a-05fb-4b3d-9be9-df0949759187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-message</value>
      <webElementGuid>86724726-b497-4d21-acfb-c6df8eb56299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Basket “Android Quick Start Guide” has been added to your basket.</value>
      <webElementGuid>35e8566c-687a-4663-85df-6dc9aadece0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;woocommerce-message&quot;]</value>
      <webElementGuid>89b0be1e-ec6d-475a-9f57-73724b8a0780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>d603f027-7e97-4f0a-abab-c12f0873ad27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[1]/following::div[1]</value>
      <webElementGuid>76829dde-95db-4757-bff0-f1ffc251df30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>f4a1a817-cd59-4f91-afc7-51ca09bab202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/preceding::div[1]</value>
      <webElementGuid>c24853ae-1619-4139-b5c1-452242e4ceae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='“Android Quick Start Guide” has been added to your basket.']/parent::*</value>
      <webElementGuid>d925587c-6497-48ee-9d95-8de969c65775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>dc564b91-4828-4733-96ba-43261b6720a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View Basket “Android Quick Start Guide” has been added to your basket.' or . = 'View Basket “Android Quick Start Guide” has been added to your basket.')]</value>
      <webElementGuid>2fefce9c-c49e-4c44-adbf-ab6a6848bfe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
