<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Remember me_rememberme</name>
   <tag></tag>
   <elementGuidId>8178cad7-9212-4cce-9096-94953473ff12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Remember me&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6c88f69-af6f-424b-a06f-daedb70f05c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-Input woocommerce-Input--checkbox</value>
      <webElementGuid>105b7234-d9ce-4297-b4ff-3763e4ce04df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberme</value>
      <webElementGuid>6040cd2b-f951-4b87-a77b-851564b42077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0a2e09f0-8c4e-4433-98d3-90b4a509e572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberme</value>
      <webElementGuid>e709bec4-89d6-4927-a8d2-7bc8a73ec868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>forever</value>
      <webElementGuid>ab76d747-a5f1-4adb-b2d1-08371cd5a7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberme&quot;)</value>
      <webElementGuid>5a9ce01d-6a7a-4204-a988-6e640637e9b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberme']</value>
      <webElementGuid>975dd036-2e15-4ab1-a387-92469f4f1c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div/form/p[3]/label/input</value>
      <webElementGuid>e5b9e66d-9cfb-4993-a342-14c9a20303ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>fcc0b46b-fa78-4ddb-8823-53c7c3ce89dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rememberme' and @type = 'checkbox' and @id = 'rememberme']</value>
      <webElementGuid>d1b3bc1a-6d65-4fae-977f-64cd5bb3a131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
